### ISSUE TITLE
Abstract HACL* Dependency into its own library

### ISSUE THREAD

**Issue by AddressXception** [microsoft/electionguard-cpp#122]
As a developer I would like the HACL* dependency to be compiled into its own library so that I can update the HACL module independently from my other code in certain circumstances.

Currently the HACL* source code is stored directly in the project.  Given that #22 is completed, the HACL library could be compiled into its own DLL.  for consumers who wish to use shared dependencies and ABI-compatible compilers the libraries can be updated independently of one another.  This also more clearly separates the interface between the electionguard code and its dependencies providing greater flexibility.

**Comment by colleenirt** [comment]
duplicate to #22?
