### ISSUE TITLE
Xamarin.iOS Segfaults with unhandled c++ exceptions

### ISSUE THREAD

**Issue by AddressXception** [microsoft/electionguard-cpp#147]
## Bug Report

**Current Behavior**
When an exception is thrown in the C++ library the mono runtime seg faults with:

`libc++abi.dylib: terminating with uncaught exception of type...`

even though the exception may be handled.

**Expected behavior/code**
In some cases, the C++ code should be able to throw exceptions that are caught by c++ `catch` clauses and recover.  Specifically, if there are only unmanaged frames in the call stack then the application should be able to continue as normal.  Since there are no instances (today) where the unmanaged code calls into managed code (i.e. there re no callback functions used) then this consideration should always hold true.  Additionally, all exceptions from c++ code should be caught in the `facade` layer and converted into status return codes when reaching across the C api boundary.

**Environment**
- OS: OSX 11.2, iOS 14.2 (simulator)

**Possible Solution**

This could be an issue with passing in the wrong or missing compier flags when building the c++ library for iOS.  It could also be an issue [propagating runtime exceptions as mentioned in the mono documentation](https://www.mono-project.com/docs/advanced/pinvoke/#runtime-exception-propagation).  Also [see the P/Invoke docs on exception marshalling](https://docs.microsoft.com/en-us/xamarin/ios/platform/exception-marshaling)

If this is a compilation error, the solution may be to provide the appropriate flags.  If this is a marshaling error, the solution may be to define a global exception handler for each platform in the platform-specific C# projects.  If we must define a global exception handler, we should also forward those events to the containing application so that consumers of the library can respond in-kind.  That likely means defining an interface and forcing the consumer to initialize the library on startup.

**Comment by AddressXception** [comment]
After talking with some folks it looks like this might be a viable spolution:

https://www.mono-project.com/docs/advanced/signals/

**Comment by keithrfung** [comment]
Closing issue until #195
