### ISSUE TITLE
📦 Create Nuget Packages with Precompiled Binaries

### ISSUE THREAD

**Issue by AddressXception** [microsoft/electionguard-cpp#17]
when publishing a release, the build system should precompile binaries so that users can pull in the dependencies without having to build from source.

additionally, users should be able to verify the integrity of the precompiled binaries so that they can be sure the binaries were compiled by the correct authority

**Comment by keithrfung** [comment]
Some tools and guidance around this issue that we're considering:

https://github.com/dockcross/dockcross
https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting
https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/nuget
https://www.c-sharpcorner.com/article/create-shared-library-or-nuget-package-in-net-core-application/
https://github.com/novotnyllc/MSBuildSdkExtras

The focus currently is to complete builds for .net 2.0 and .net framework 4.8
These will be packages needed for Nuget and have to build x86 and x64
