### ISSUE TITLE
🔐. Encrypt Extended Data for Contests and Selections

### ISSUE THREAD

**Issue by AddressXception** [microsoft/electionguard-cpp#173]
Currently, the code stubs out the `extended_data` field but the field cannot properly be used until it is encrypted. This will require a new type of elgamal encryption to be implemented. 

- [ ] Ensure extended_data exists on contests and selections for ballots
- [ ] Encrypt (and Decrypt) extended data through normal encryption process
- [ ] Add tests

**Comment by colleenirt** [comment]
this depends on both Jeff's precomute as well as matches what is in Python

**Comment by colleenirt** [comment]
waiting on change in Steve's  PR 262
