### ISSUE TITLE
ContestDescription missing party ids

### ISSUE THREAD

**Issue by AddressXception** [microsoft/electionguard-cpp#174]
## Bug Report

**Expected Behavior**
Contest descritpions include party id's when necessary

**Actual Behavior**
party id's are not included. there is a missing field.

**Environment**
- OS: [e.g. OSX 10.13.4, Windows 10]
- Version: [e.g. 1.0.1]

**Comment by gusmccallum** [comment]
Hi I'd like to work on this, please assign it to me.
