### ISSUE TITLE
Add native 32 bit support

### ISSUE THREAD

**Issue by AddressXception** [microsoft/electionguard-cpp#180]
## Feature Request

**Description**
As a developer i would like to optimize bignum calculations for 32 bit processors so that I can gain better performance on 32 bit platforms.  

HACL includes support for native 32-bit width bignums, however because of the way the bignums are laid out in memory, we must use an internal type alias anywhere uint64_t is currently used (in relation to ElementModP and ElementModQ).  This ticket is to refactor the code base to consume uint32_t or uint64_t bignum arrays where needed.

**Comment by lmarie79** [comment]
@AddressXception - is this case still valid?
