### ISSUE TITLE
Match Python Serialization Changes

### ISSUE THREAD

**Issue by AddressXception** [microsoft/electionguard-cpp#183]
## Feature Request

**Description**
The python code recently made adjustments to serialization.  This issue is to ensure that the changes did not break interoperability between the python and c++ code.  the work was done in [PR #394](https://github.com/microsoft/electionguard-python/pull/394)

To Test:
1. Ensure the sample data is well formed.
2. export some ballots
3. import them into python
4. validate that the ballot import functionality still works as expected.

**Comment by lmarie79** [comment]
@AddressXception - can we remove the "question" tag or is there still a question outstanding?
