### ISSUE TITLE
🧹 Resolve build warning: C4035 Truncation 

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-cpp#217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

Resolve C4305 error surrounding truncation.

These can be seen in this [example run](https://github.com/microsoft/electionguard-cpp/pull/215/checks?check_run_id=3953853235) under `windows-2019-gcc-9.2.0` or `windows-2019-msvc-latest`. 

**Example:** 
> warning C4305: 'return': truncation from 'eg_electionguard_status_e' to 'bool' [D:\a\electionguard-cpp\electionguard-cpp\build\libs\msvc\Win32\src\electionguard.vcxproj]

### Anything else?

MSDocs:
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4305?view=msvc-160

**Comment by SteveMaier-IRT** [comment]
Matt already fixed this code.
