### ISSUE TITLE
🧹  Resolve XML comment warnings for C# project

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-cpp#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

During the compilation of the the C# project in bindings, there are errors related specifically to XML comments. These should be easily resolved with some `/// summary` tags. The descriptions can be pulled from the python repo or the underlying c code, whichever is easier. 

These can be seen in this [example run](https://github.com/microsoft/electionguard-cpp/pull/215/checks?check_run_id=3953853235) under `windows-2019-gcc-9.2.0` or `windows-2019-msvc-latest`. 

### Examples
The following warnings: 
>  warning CS1570: XML comment has badly formed XML -- 'End tag 'summary' does not match the start tag 'sumary'.'

> warning CS1572: XML comment has a param tag for 'nonceSeed', but there is no parameter by that name

> warning CS1573: Parameter 'verifyProofs' has no matching param tag in the XML comment...

> warning CS1591: Missing XML comment for publicly visible type or member 

### Possible Implementation

Add XML comments for the c sharp members

https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1570
https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1572
https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1573
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1591

### Anything else?

Replaces Issue #188

**Comment by askalik** [comment]
Can I take this one?

**Comment by keithrfung** [comment]
@askalik you got it!
