### ISSUE TITLE
Consume HACL* as an external Dependency

### ISSUE THREAD

**Issue by AddressXception** [microsoft/electionguard-cpp#22]
As a developer I would like the HACL* dependency to be referenced directly from the source repository's distribution so that I can upgrade the library easily by incrementing the dependency version number

The core crypto library [HACL*](https://github.com/project-everest/hacl-star) is currently referenced directly in the source code.  This is problematic for a variety of reasons but namely it is prone to transcription errors when updating the code base.

We should instead use a scheme to load the HACL dependency at compile time and cache the results unless a new version is required.  One approach to accomplish this would be to use cmake to pull the relevant source files and cache them in the project.

**Comment by lmarie79** [comment]
@AddressXception - should this be combined with #122 or one of them closed out?

**Comment by colleenirt** [comment]
duplicate to #122?
