### ISSUE TITLE
✨  Handle accepting Overvotes

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-cpp#226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

Overvotes occur when the selection limit is exceed on a contest on a ballot. This is to use extended_data and other tools to handle overvotes. 

This will require adding configuration and ensuring that extended_data is already encrypted (#173)

**Comment by colleenirt** [comment]
@jeffspel_crypto this is the next subset of work
