### ISSUE TITLE
Hashing should use mod q not mod q-1

### ISSUE THREAD

**Issue by lmarie79** [microsoft/electionguard-cpp#232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Today: hash.py is computing its result modulo `q-1`. This is an unusual choice but for the most part doesn't really matter, except when it does. With the HACL library, used in electionguard-cpp, the function `Hacl_Bignum256_mod()` has the constraint that it requires the modulus to be an odd number. `q` is odd. `q-1` is even.

The "obvious" solution here is to just replace `q-1` with `q`. This will have no meaningful impact on security or anything else, but will make implementations of ElectionGuard using HACL much easier to build correctly.

**Comment by SteveMaier-IRT** [comment]
For the C++ code, Matt and I have already checked and this is not a problem.
