### ISSUE TITLE
✨ Standardize Whitespace

### ISSUE THREAD

**Issue by lprichar** [microsoft/electionguard-cpp#249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

The whitespace is inconsistent across files.  Sometimes it uses unix style line endings and sometimes it uses Windows.

### Possible Implementation

1. Fix with something like this (if on Windows):

`find . -type f -exec dos2unix -k -s -o {} ';'`

2. Add a .gitattributes file to ensure the repo uses unix line endings but checks out as windows line endings on windows.  Something like `* text=auto`, see also: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Comment by MatthewRatzell** [comment]
Hey all, I would love to contribute to the project and think this would be a good issue to start with, I am unsure if I'll be able to solve it, but I am going to do my best to get it done. Regardless I'll be in quick communication, so if I have any troubles I won't be leaving you all in the dark.
