### ISSUE TITLE
🐞 The benchmarking tests are hanging (it may be that they actually are just taking a really long time to finish)

### ISSUE THREAD

**Issue by jeffspel-crypto** [microsoft/electionguard-cpp#264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The introduction of the precomputation benchmarking tests caused the benchmarking overall test to hang (it may be that they are they are really just taking a really long time to finish). The issue is that one of the benchmark cases is performing a large number of precomputations in setup code (this can take a very long time) and the stop_populate call isn't being made. The fix is to call stop_populate before performing the benchmark.

### Expected Behavior

The benchmark tests complete in a reasonable amount of time.

### Steps To Reproduce

1. I ran the benchmarking test on Windows but I would expect this to occur on any platform.
2. Run "make bench".
3. Notice that it looks like the test hangs for a long time.

### Environment

```markdown
- OS: Windows 10
```

**Comment by SteveMaier-IRT** [comment]
Code updates seem to have resolved this already.  Closing.
