### ISSUE TITLE
Device class should be serializable

### ISSUE THREAD

**Issue by SteveMaier-IRT** [microsoft/electionguard-cpp#280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

The Device class in the cpp repo is not serializable like the ones in the python repos.  This should be added so that the device can be created from a json string and also serialized back out to be saved as a json file.

This needs to be accessible from the .NET Standard code like the manifest and context are.

**Comment by MatthewRatzell** [comment]
feel free to assign me to this. Ill take care of this on Saturday
